/// Types of daily missions generated by Compass Engine.
enum MissionType {
  speakMinutes,
  completeSession,
  reviewExpressions,
  recordSpeech,
  addNotebookItem,
  practiceSkill,
}

enum MissionStatus {
  pending,
  inProgress,
  completed,
  skipped,
  expired,
}

enum GoalPeriod {
  daily,
  weekly,
  custom,
}

enum GoalStatus {
  active,
  completed,
  paused,
  archived,
}
